name: Checkout repo and setup Node, Python
description: realm_bot composite action for setting up jobs

inputs:
  token:
    description: alternative GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Node dependencies
      shell: bash
      run: npm ci

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python-version: 3.12

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install -U pip setuptools
        pip install -e .[dev,docs]
