[bot]
data_folder = "data"
help_command = "help"
extensions = ["aethersprite.extensions.base._all", "rpgbot._all"]
owner = "haliphax#4859"
prefix = "!"
token = "SOMEREALLYLONGSTRINGTHATDISCORDGIVESYOU"

[webapp]
host = "0.0.0.0"
port = 5000
